source 'https://rubygems.org'
ruby '2.0.0'
 
gem 'rails', '4.0.2'
gem 'pg'
gem 'devise'
gem 'cancan'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'dotenv-rails'
gem 'omniauth'
gem 'omniauth-facebook', '1.4.0'
gem 'bootstrap-sass'
 
group :development do
	gem 'pry-rails'
	gem 'better_errors'
	gem 'binding_of_caller'
	gem 'annotate'
	gem 'bullet'
  gem 'debugger'
  gem 'localtunnel'
  gem 'lol_dba'
  gem 'meta_request'
  gem 'quiet_assets'
  gem 'rack-mini-profiler'
  gem 'rails-erd'
  gem 'rails_best_practices'
  gem 'rails-footnotes'
  gem 'smusher'
  gem 'rails_layout'
end


